# Generated by Django 4.1.1 on 2023-02-12 21:04

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('total_amount', models.ImageField(default=0, upload_to='', validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('address_city', models.CharField(max_length=50)),
                ('address_street', models.CharField(max_length=50)),
                ('address_ZIP', models.CharField(max_length=10)),
                ('address_home_number', models.CharField(max_length=5)),
                ('img_manufacturer', models.ImageField(upload_to='author_img')),
                ('activ', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Oder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('total_amount', models.ImageField(default=0, upload_to='', validators=[django.core.validators.MinValueValidator(0)])),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_shipping', models.DateTimeField(null=True)),
                ('status', models.CharField(choices=[('UNF', 'angenommen'), ('CON', 'bestätigt'), ('COL', 'gesammelt'), ('SHI', 'verschickt')], default='UNF', max_length=3)),
                ('payment_type', models.CharField(choices=[('PP', 'PayPal'), ('BG', 'Bar')], default='BG', max_length=2)),
                ('payment_status', models.CharField(choices=[('PAI', 'bezahlt'), ('UNP', 'unbezahlt')], default='UNP', max_length=3)),
                ('address_city', models.CharField(max_length=20)),
                ('address_ZIP', models.CharField(max_length=5)),
                ('address_street', models.CharField(max_length=50)),
                ('address_home_number', models.CharField(max_length=5)),
                ('address_last_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('discount', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('image', models.ImageField(upload_to='product_img')),
                ('amount', models.IntegerField()),
                ('active', models.BooleanField(default=False)),
                ('composition', models.JSONField(default={})),
                ('manufacturer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.manufacturer')),
            ],
        ),
        migrations.CreateModel(
            name='OderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('oder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.oder')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.product')),
            ],
        ),
        migrations.CreateModel(
            name='CartLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('discount', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.cart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
            ],
        ),
    ]
