# Generated by Django 4.0 on 2023-03-28 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_manufacturer_options_remove_order_purchaser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ip',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='address_ZIP',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AlterField(
            model_name='order',
            name='address_city',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='address_home_number',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AlterField(
            model_name='order',
            name='address_last_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='address_street',
            field=models.CharField(default='', max_length=50),
        ),
    ]
