# Generated by Django 4.0 on 2023-04-24 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_delivery_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='ip',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
