# Generated by Django 4.1.1 on 2023-09-13 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_alter_cart_ip'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thumbnail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='thumbnails_img')),
            ],
            options={
                'verbose_name': 'Bild',
                'verbose_name_plural': 'Bilder',
                'ordering': ['title'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='thumbnail',
            field=models.ManyToManyField(related_name='product', to='shop.thumbnail'),
        ),
    ]
