# Generated by Django 4.1.1 on 2023-09-13 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_category_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='composition',
            name='title',
            field=models.CharField(max_length=150),
        ),
    ]
