# Generated by Django 4.1.1 on 2023-09-13 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_product_subtitle_product_wight_alter_product_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='wight',
        ),
    ]
