# Generated by Django 4.1.1 on 2023-09-13 11:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_remove_product_wight'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='wight',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
