# Generated by Django 4.1.1 on 2023-09-13 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_remove_product_wight'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='wight',
            field=models.CharField(default='', max_length=150),
        ),
    ]
