# Generated by Django 4.1.1 on 2023-09-13 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_product_wight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='subtitle',
        ),
        migrations.RemoveField(
            model_name='product',
            name='wight',
        ),
    ]
