# Generated by Django 4.1.1 on 2023-09-13 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_product_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='weight',
        ),
    ]
