# Generated by Django 4.1.1 on 2023-09-13 15:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_remove_product_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(1)]),
            preserve_default=False,
        ),
    ]
