# Generated by Django 4.1.1 on 2023-09-13 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0024_product_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='subtitle',
            field=models.CharField(default='', max_length=150),
        ),
    ]
