# Generated by Django 4.1.1 on 2023-09-13 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0025_product_subtitle'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=50)),
                ('answer', models.TextField()),
            ],
        ),
    ]
