# Generated by Django 4.1.1 on 2023-09-14 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0026_faq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='thumbnail',
            field=models.ManyToManyField(blank=True, related_name='product', to='shop.thumbnail'),
        ),
    ]
