# Generated by Django 4.1.1 on 2023-09-14 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0030_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cooking',
            field=models.TextField(default=''),
        ),
    ]
