# Generated by Django 4.1.1 on 2023-09-14 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0031_alter_product_cooking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cooking',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
