# Generated by Django 4.1.1 on 2023-09-14 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0032_alter_product_cooking_alter_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='prepared',
            field=models.BooleanField(default=False),
        ),
    ]
