# Generated by Django 4.1.1 on 2023-09-18 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0034_alter_faq_options_alter_product_options_product_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='date',
            new_name='date_created',
        ),
    ]
