# Generated by Django 4.1.1 on 2023-09-19 21:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0037_cartitem_total_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_cost', models.IntegerField(default=7, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
            ],
            options={
                'verbose_name': 'Steuer',
                'verbose_name_plural': 'Steuern',
                'ordering': ['id'],
            },
        ),
        migrations.RenameField(
            model_name='order',
            old_name='total_amount',
            new_name='products_amount',
        ),
        migrations.AddField(
            model_name='order',
            name='products_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
