# Generated by Django 4.1.1 on 2023-09-19 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0038_tax_rename_total_amount_order_products_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='phone_number',
            field=models.CharField(default='', max_length=20),
        ),
    ]
