# Generated by Django 4.1.1 on 2023-09-19 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0039_order_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thumbnail',
            name='image',
            field=models.ImageField(upload_to='thumbnails_img'),
        ),
    ]
