# Generated by Django 4.1.1 on 2023-09-20 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0040_alter_thumbnail_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='vendor',
            field=models.CharField(default='9-', max_length=15),
        ),
    ]
