# Generated by Django 4.1.1 on 2023-09-21 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0042_rename_vendor_product_vendor_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ip',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
